### PR TITLE
Grant weapon license issue for shop

### PR DESCRIPTION
**Pull request by mjvanhaastert**
The shop doesnt grab the new playerdata after granting the license player needs to relog so the shop gets the new data onplayerload this solves this issue

full description is here #117

### CODE REVIEW

**Comment by amantu-qbit** [comment]
Fix the Lint issue Please and Branch is Out of Date

**Comment by mjvanhaastert** [comment]
> 

it was edited on github, it cant be out of date?

**Comment by amantu-qbit** [comment]
Yeah it can, If any new PR merges after this PR this PR will go Out of Date

**Comment by amantu-qbit** [comment]
For fixing the Linting issue try to use a different name for Local and Global Variable. Cause otherwise, It's Shadowing other one's value.

**Comment by r0adra93** [comment]
The error you attempted to fix was addressed and merged into the system.

**Pull request closed without merging**
