### PR TITLE
update: polyzone & target integration

### PR DESCRIPTION
**Pull request by izMystic**
Integrates Polyzone, qb-target, and qb-core NUI Draw Text

Closes
- #61 
- #60 
- #58 
- #59

### CODE REVIEW

**Review by Kingsage311 — COMMENTED** [review]
image

Errors with this PR  Unless there's a Convar for use target is in the new core this pr does not work as is

**Comment by DannysRP** [comment]
I did test this and the target options are shared between all peds

**Comment by izMystic** [comment]
Like, every ped on the map? Or just the models in config?

**Comment by DannysRP** [comment]
The set models in the config. Like the shop keeps for 24/7s, LTDs, Robs Liquors. They all have multiple target options

**Comment by izMystic** [comment]
Ah that's what you mean, I'll look into it tomorrow

**Comment by izMystic** [comment]
> The set models in the config. Like the shop keeps for 24/7s, LTDs, Robs Liquors. They all have multiple target options

that issue should be fixed

**Comment by DannysRP** [comment]
Are you able to make shops without a ped?

**Comment by izMystic** [comment]
i did it without peds at first, but people wanted peds
https://github.com/qbcore-framework/qb-shops/pull/65/commits/bd38d4e16def44a65ed9d0ae4f9130c5481f355c

**Comment by izMystic** [comment]
as of there, it wasnt using peds

**Comment by DannysRP** [comment]
There is an error paired with the trucker job when completing deliveries that comes from qb-shops. Not sure if it's because of this PR 
image

**Comment by izMystic** [comment]
and the no license issue seems to be a problem with qb-inventory as it doesnt do that with lj-inventory

**Comment by izMystic** [comment]
nevermind, issue still persists with lj-inventory

**Pull request merged**
