### PR TITLE
Added black market capabilities with markup

### PR DESCRIPTION
**Pull request by WizardTux**
**Describe Pull request**
Adds the ability to bypass the license requirement on a per shop basis, without having to create a separate shop / weapons list. Its probably not perfect or completely optimized.

If your PR is to fix an issue mention that issue here: N/A

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? -- Yes
- Does your code fit the style guidelines? -- I guess? I didn't see this posted anywhere.
- Does your PR fit the contribution guidelines? -- I guess, I didn't see this posted anywhere.

### CODE REVIEW

**Comment by tom-osborne** [comment]
Has conflicts

**Comment by r0adra93** [comment]
local products = Config.Locations[shop].products
    local products = deepCopy(Config.Locations[shop].products)
    
    do the same thing!
    Your version SUCKS UP MORE CPU-CLOCK CYCLES

**Review by r0adra93 — COMMENTED** [review]
local products = Config.Locations[shop].products
    local products = deepCopy(Config.Locations[shop].products)
    
    do the same thing!
    Your version SUCKS UP MORE CPU-CLOCK CYCLES
   
   fix it!

**Comment by rodrigoandrade1** [comment]
Hello, thanks for wanting to improve qb-shops, we've looked at your PR and it's a good idea, but a little poorly executed. Soon we will try to add a similar function.

**Pull request closed without merging**
