### PR TITLE
fix bad argument to 'joaat' (string expected, got nil)

### PR DESCRIPTION
**Pull request by martink1337**
Client issue which happens when you just join an server with latest version of all resources and you will see the error in your client console.

**Describe Pull request**
First, make sure you've read and are following the contribution guidelines and style guide and your code reflects that.
Write up a clear and concise description of what your pull request adds or fixes and if it's an added feature explain why you think it should be included in the core.

If your PR is to fix an issue mention that issue here

**Questions (please complete the following information):**
- Have you personally loaded this code into an updated qbcore project and checked all it's functionality? [yes/no] (Be honest)
- Does your code fit the style guidelines? [yes/no]
- Does your PR fit the contribution guidelines? [yes/no]

### CODE REVIEW

**Comment by GodyFromDiscord** [comment]
I cannot reproduce this on a brand new qb-core server created 15 minutes ago

**Review by rody05 — COMMENTED** [review]
This doesn't make sense, if the type of v["ped"] is a number then it is already the hash of the ped, the problem is that this is a nil value.

**Comment by HighCaliber50** [comment]
I get an error for this line constantly. Can I just comment it out? what does it do even?

**Comment by DJJackal** [comment]
Anyone have a solution?

**Pull request closed without merging**
