### PR TITLE
Configurable Icons/Labels/Scenarios/Blip Colors

### PR DESCRIPTION
**Pull request by DannysRP**
- Configurable Icons/Labels/Scenarios for shop peds.
- Configurable Blip Colors
- Change 'Sell Chips' icon to coins from cookie.

### CODE REVIEW

**Comment by Andyauk** [comment]
this is great. thanks.

**Comment by Andyauk** [comment]
```
    ["weedshop"] = {
        ["label"] = "Smoke On The Water",
        ["coords"] = vector4(-1171.31, -1570.89, 4.66, 130.03),
        ["ped"] = 'a_m_y_hippy_01',
        ["scenario"] = "WORLD_HUMAN_AA_SMOKE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-cannabis",
        ["targetLabel"] = "Open Weed Shop",
        ["products"] = Config.Products["weedshop"],
        ["showblip"] = true,
        ["blipsprite"] = 140.
        ["blipcolor"] = 0
```
needs changing to , not . on blipsprite.

**Comment by DannysRP** [comment]
This should be good now

**Comment by Andyauk** [comment]
```
    ["hardware3"] = {
        ["label"] = "Hardware Store",
        ["coords"] = vector4(-421.83, 6136.13, 31.88, 228.2),
        ["ped"] = 'mp_m_waremech_01',
        ["scenario"] = "WORLD_HUMAN_CLIPBOARD",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-wrench",
        ["targetLabel"] = "Hardware Store",
        ["products"] = Config.Products["hardware"],
        ["showblip"] = true,
        ["blipsprite"] = 402,
        ["blipcolor"] = 0,
    },
```

 ["blipcolor"] = 0, not sure if this was intended the ,

**Comment by DannysRP** [comment]
Remove it lol

**Comment by Andyauk** [comment]
im not good at PR,. but you can use this if you like.

```
    ["coffeeplace"] = {
        [1] = {
            name = "coffee",
            price = 5,
            amount = 500,
            info = {},
            type = "item",
            slot = 1,
        },
        [2] = {
            name = "lighter",
            price = 2,
            amount = 50,
            info = {},
            type = "item",
            slot = 2,
        },
    },

    -- Bean Coffee Locations
    ["beancoffee"] = {
        ["label"] = "Bean Machine Coffee",
        ["coords"] = vector4(-628.97, 238.27, 81.9, 1.28),
        ["ped"] = `A_F_Y_Hipster_02`,
        ["scenario"] = "WORLD_HUMAN_STAND_MOBILE",
        ["radius"] = 1.5,
        ["targetIcon"] = "fas fa-shopping-basket",
        ["targetLabel"] = "Open Shop",
        ["products"] = Config.Products["coffeeplace"],
        ["showblip"] = true,
        ["blipsprite"] = 52,
        ["blipcolor"] = 0
    },
```

**Pull request merged**
