### PR TITLE
Adding config option to disable firearms license check in gun shops

### PR DESCRIPTION
**Pull request by charj**
This pr adds an option to disabel the firearms license check in gun shops to the configuration.

**- Have you personally loaded this code into an updated qbcore project and checked all it's functionality?**
Of course.
**- Does your code fit the style guidelines?**
Yes
**- Does your PR fit the contribution guidelines?**
Yes

### CODE REVIEW

**Review by r0adra93 — CHANGES_REQUESTED** [review]
I did the same thing and was about to submit it.

Move your check up a line.

to 

if data.type == "weapon" and Config.FirearmsLicenseCheck (I would change check to Enabled) set to true

**Comment by charj** [comment]
> I did the same thing and was about to submit it.
> 
> Move your check up a line.
> 
> to
> 
> if data.type == "weapon" and Config.FirearmsLicenseCheck (I would change check to Enabled) set to true

If the check is moved to the above condition, the success message will not be seen

**Comment by r0adra93** [comment]
exactly, there's no need for the dealer to verify anything. The feature is disabled, there's no real need to run extra code.

**Comment by charj** [comment]
> exactly, there's no need for the dealer to verify anything. The feature is disabled, there's no real need to run extra code. One of the best parts of disabling a feature is that it saves resources, no need to process extra data if it isn't going to be used.

Updated!

**Comment by r0adra93** [comment]
I've been watching! LOL i'm grabbing code now to test.

**Review by r0adra93 — APPROVED** [review]
tested, works flawlessly, no errors, guns aren't sold without a permit when enabled and are sold without a permit when disabled.

**Pull request merged**
